"""test

Revision ID: 0f3541a1e6f3
Revises: 88179e39cf1e
Create Date: 2026-03-24 13:29:21.618024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3541a1e6f3'
down_revision: Union[str, Sequence[str], None] = '88179e39cf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grids', sa.Column('message_repost_text', sa.String(), nullable=True))
    op.add_column('grids', sa.Column('message_link_text', sa.String(), nullable=True))
    op.add_column('grids', sa.Column('message_bad_text', sa.String(), nullable=True))
    op.add_column('grids', sa.Column('message_stop_word_text', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('message_repost_text', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('message_link_text', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('message_bad_text', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('message_stop_word_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'message_stop_word_text')
    op.drop_column('groups', 'message_bad_text')
    op.drop_column('groups', 'message_link_text')
    op.drop_column('groups', 'message_repost_text')
    op.drop_column('grids', 'message_stop_word_text')
    op.drop_column('grids', 'message_bad_text')
    op.drop_column('grids', 'message_link_text')
    op.drop_column('grids', 'message_repost_text')
    # ### end Alembic commands ###
