"""create message

Revision ID: da39383104d0
Revises: 129773955d5d
Create Date: 2026-04-20 22:41:07.718862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da39383104d0'
down_revision: Union[str, Sequence[str], None] = '129773955d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_block_users',
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('grid_id', 'user_id')
    )
    op.add_column('users', sa.Column('max_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_id')
    op.drop_table('grid_block_users')
    # ### end Alembic commands ###
