"""test

Revision ID: e63166919ae0
Revises: 
Create Date: 2026-03-22 23:26:30.357315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63166919ae0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bad_words', sa.Boolean(), nullable=False),
    sa.Column('repost', sa.Boolean(), nullable=False),
    sa.Column('stop_word', sa.Boolean(), nullable=False),
    sa.Column('link', sa.Boolean(), nullable=False),
    sa.Column('message_delete', sa.Boolean(), nullable=False),
    sa.Column('message_delete_text', sa.String(), nullable=False),
    sa.Column('bad_words_text', sa.Text(), nullable=True),
    sa.Column('stop_word_text', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('bad_words', sa.Boolean(), nullable=False),
    sa.Column('repost', sa.Boolean(), nullable=False),
    sa.Column('stop_word', sa.Boolean(), nullable=False),
    sa.Column('link', sa.Boolean(), nullable=False),
    sa.Column('message_delete', sa.Boolean(), nullable=False),
    sa.Column('message_delete_text', sa.String(), nullable=False),
    sa.Column('bad_words_text', sa.Text(), nullable=True),
    sa.Column('stop_word_text', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('grid_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('users')
    op.drop_table('grids')
    # ### end Alembic commands ###
