"""create message

Revision ID: eec7d9a0b2de
Revises: 0f3541a1e6f3
Create Date: 2026-04-19 22:09:50.754449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec7d9a0b2de'
down_revision: Union[str, Sequence[str], None] = '0f3541a1e6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'position')
    # ### end Alembic commands ###
